name: Manual Publish

on:
    workflow_dispatch:

concurrency:
    group: manual-publish-${{ github.sha }}
    cancel-in-progress: false

jobs:
    manual-publish:
        name: Manual Publish Trigger
        uses: NextNodeSolutions/github-actions/.github/workflows/publish-release.yml@main
        permissions:
            contents: write
            id-token: write
            actions: read
            packages: write
        with:
            node-version: '24'
            pnpm-version: '10.11.0'
            publish-script: 'changeset:publish'
            build-script: 'build'
            enable-provenance: true
            create-github-release: true
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
