name: Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  quality-checks:
    name: Quality Checks
    uses: NextNodeSolutions/github-actions/.github/workflows/quality-checks.yml@main
    with:
      run-lint: true
      run-typecheck: true
      run-tests: true
      run-build: true
      test-coverage: true
      node-version: '24'
      pnpm-version: '10.11.0' 