name: Tests

on:
    pull_request:
        branches: [main, master]

jobs:
    quality-checks:
        name: Quality Checks
        uses: NextNodeSolutions/github-actions/.github/workflows/quality-checks.yml@main
        with:
            run-lint: true
            run-typecheck: false
            run-tests: false
            run-build: false
            test-coverage: false
