name: Version Management

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: version-${{ github.ref }}
    cancel-in-progress: false

jobs:
    version-management:
        name: Version Management
        uses: NextNodeSolutions/github-actions/.github/workflows/version-management.yml@main
        permissions:
            contents: write
            pull-requests: write
            actions: read
        with:
            version-script: 'changeset:version'
            auto-merge: true
